# -*- coding: utf-8 -*-
"""Motor_de_Busca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkxQ0dAHlk5HFqwCH_Q-teCycca72ZY6
"""

pip install pandas

import requests
from bs4 import BeautifulSoup


response = requests.get('https://g1.globo.com/')

content = response.content

site = BeautifulSoup(content, 'html.parser')

# HTML da notícia
noticia = site.find('div', attrs={'class': 'feed-post-body'})

# Título
titulo = noticia.find('a', attrs={'class': 'feed-post-link'})

print(titulo.text)

# Subtítulo: div class="feed-post-body-resumo"
subtitulo = noticia.find('div', attrs={'class': 'feed-post-body-resumo'})

print(subtitulo.text)

pip install requests
pip install bs4

import requests
from bs4 import BeautifulSoup

Aidor = input("Nome do Aidor: ")
url = f"https://pocamarket.com/search?search_type=normal&sort=new&q={Aidor}"

response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, 'html.parser')

# Encontrar todas as divs com a classe 'w-full cursor-pointer', responsáveis por cada card
artistas = soup.find_all("div", attrs={"class": "w-full cursor-pointer"})

for poca in artistas:
    # Inicializar as listas de dados para cada artista
    dados_artista = []

    # Encontrar e armazenar dados do artista
    artista = poca.find('div', class_='grid-card__info__profile__name__member').text.strip()
    preco = poca.find('div', class_='grid-card__info__price').text.strip()
    album = poca.find('div', class_='grid-card__info__card-name').text.strip()
    grupo_elemento = poca.find('div', class_='grid-card__info__profile__logo')
    grupo = grupo_elemento.find_next('img')['alt'].strip() if grupo_elemento else "Não encontrado"
    imagem_url = poca.find('div', class_='grid-card__image').find_next('img')['src'].strip()

    # Encontrar a URL da imagem do grupo
    grupo_imagem_url = grupo_elemento.find_next('img')['src'].strip() if grupo_elemento else "Não encontrado"

    # Encontrar a URL da imagem do artista
    imagem_url = poca.find('div', class_='grid-card__image').find_next('img')['src'].strip()
    dados_artista.append({
        "Artista": artista,
        "Grupo": grupo,
        "Preço": preco,
        "Álbum": album,
        "Imagem URL Artista": imagem_url,
        "Imagem URL Grupo": grupo_imagem_url
    })

    # Imprimir dados para cada artista
    print("Dados do artista:")
    print("------------------")
    for dado in dados_artista:
        for chave, valor in dado.items():
            print(f"{chave}: {valor}")
        print("====================================")
        print("\n")